sudo: required
services:
    - docker

before_install:
    - docker build --pull --rm -f "./client/Dockerfile.dev" -t rafaelsantosxp/react-test "client"

script:
    - docker run rafaelsantosxp/react-test npm test -- --coverage

after_sucess:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker build -t rafaelsantosxp/multi-client ./client
    - docker push rafaelsantosxp/multi-client

    - docker build -t rafaelsantosxp/multi-nginx ./nginx
    - docker push rafaelsantosxp/multi-nginx

    - docker build -t rafaelsantosxp/multi-server ./server
    - docker push rafaelsantosxp/multi-server

    - docker build -t rafaelsantosxp/multi-worker ./worker
    - docker push rafaelsantosxp/multi-worker    

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'atendimento'
  env: 'Atendimento-env'
  bucket_name: 'elasticbeanstalk-us-east-1-557187358524'
  bucket_path: 'atendimento'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY