sudo: required
services:
    - docker

before_install:
    - docker build --pull --rm -f "./client/Dockerfile.dev" -t rafaelsantosxp/react-test "client"

script:
    - docker run rafaelsantosxp/react-test npm test -- --coverage

after_sucess:
    - docker build -t rafaelsantosxp/multi-client ./client
    - docker build -t rafaelsantosxp/multi-nginx ./nginx
    - docker build -t rafaelsantosxp/multi-server ./server
    - docker build -t rafaelsantosxp/multi-worker ./worker
    # Log in Docker registry
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push images
    - docker push rafaelsantosxp/multi-client
    - docker push rafaelsantosxp/multi-nginx
    - docker push rafaelsantosxp/multi-server
    - docker push rafaelsantosxp/multi-worker